### ISSUE TITLE
Javascript/CSS Files not being read when uploaded to github

### ISSUE THREAD

**Issue by cashhelman** [thomasvaeth/trophy-jekyll#40]
Hey Thomas,
First of all, great work with this theme. I've been using wordpress for blogging, but recently decided to try to switch over to Jekyll. This is my first time I am ever using github or even attempting to use the terminal (a.k.a. I have no idea what I am doing), so perhaps the mistake I'm making are really simple. 

My issue is on the local host everything looks fine; however, when I try to upload the files onto github and connect it to my chosen domain, the browser only outputs html. Also, when I click on the links, github notifies me that the files don't exist. 

I'd greatly appreciate any help.

All the best,
Cash 
https://github.com/mynameiscash/mynameiscash.github.io
http://mynameiscash.com/
<img width="1070" alt="screen shot 2017-12-22 at 11 47 00 am" src="https://user-images.githubusercontent.com/9780255/34283401-d71dfe6e-e70e-11e7-99a4-5f76df9a9d05.png">

**Comment by cashhelman** [comment]
Figured it out! 

But I have one more question! Im currently using Chrome and it appears that when you hover over the  "View All" on the Categories tab, there is a small glitch in the CSS/JS that causes the button to  glitch instead of gradually change to brown.  It also occurs on your jekyll demo page. Is that just occuring on my particular browser?

Thanks again for your help.

-Cash

<img width="753" alt="screen shot 2017-12-22 at 4 03 32 pm" src="https://user-images.githubusercontent.com/9780255/34288665-d873d9f0-e731-11e7-9e0d-f7a874a8cfa3.png">

**Comment by cashhelman** [comment]
Sorry! I have one more question. Last one, I swear. I have two branches on my repo: gh-branch and master. Do I need both of them? I looked at your main website and it looks like you only have a master branch to host your main website. Is the gh-branch even needed?

**Comment by thomasvaeth** [comment]
– I noticed the button hover has stopped working at some point over the last couple of weeks. It definitely has something to do with updates to Chrome because it still works on Firefox and Safari. This theme is pretty old, so I haven't looked into updating it.

– It depends what repo you are using. I see you are using mynameiscash.github.io, so the gh-pages branch isn't needed, but you only get one of those repos per account. If it was a different repo, then you would need gh-pages. You would just run jekyll build and put only the files in the _site folder on the gh-pages branch. You may need the gh-pages branch still because the categories generator is weird.
