### ISSUE TITLE
Readme for awesome fonts in config not clear enough to implement 

### ISSUE THREAD

**Issue by phoenixperry** [thomasvaeth/trophy-jekyll#42]
The documentation for how to get awesome fonts up and working in the config isn't enough for me to implement it. I have tried every variation I can think of and I just can't work out what you want there to parse a twitter icon. Maybe include an actual example of the most popular icons like twitter, facebook and instagram.

**Comment by thomasvaeth** [comment]
https://github.com/thomasvaeth/trophy-jekyll/blob/development/_config.yml You can refer to my development branch that has an actual example.

https://github.com/thomasvaeth/trophy-jekyll/blob/master/_layouts/post.html You could also search for "social" and see how those files are looped through. Instead of having to write fa-twitter like the instructions on Font Awesome you simply have to write twitter.
